In [3]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

In [4]:
df1=DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})
df2=DataFrame({'key':['a','b','d'],'data2':range(3)})
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [6]:
pd.merge(df1, df2,on='key')


key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [11]:
df3=DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})
df4=DataFrame({'rkey':['a','b','d'],'data2':range(3)})
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [12]:
pd.merge(df1,df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [13]:
df1=DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})
df2=DataFrame({'key':['a','b','a','b','d'],'data2':range(5)})
pd.merge(df1, df2, on='key', how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [14]:
pd.merge(df1,df2,how='inner')

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [17]:
left=DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one'],'lval':[1,2,3]})
right=DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'rval':[4,5,6,7]})
pd.merge(left,right,on=['key1','key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [19]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [20]:
left1=DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})
right1=DataFrame({'group_val':[3.5,7]},index=['a','b'])
pd.merge(left1,right1,left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [23]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [24]:
lefth=DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],'key2':[2000,2001,2002,2001,2002],'data':np.arange(5.)})
righth=DataFrame(np.arange(12).reshape((6,2)),index=[['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],[2001,2000,2000,2000,2001,2002]],columns=['event1','event2'])

In [25]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

In [26]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [28]:
left2=DataFrame([[1.,2.],[3.,4.],[5,6]],index=['a','c','e'],columns=['Ohio','Nevada'])
right2=DataFrame([[7.,8.],[9,10],[11,12],[13,14]],index=['b','c','d','e'],columns=['Missouri','Alabama'])
pd.merge(left2,right2,how='outer',left_index=True,right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [29]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [30]:
left1.join(right1, on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [31]:
another=DataFrame([[7.,8.],[9,10],[11,12],[16,17]],index=['a','c','e','f'],columns=['New York','Oregon'])
left2.join([right2,another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [33]:
arr=np.arange(12).reshape((3,4))
np.concatenate([arr,arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
s1=Series([0,1], index=['a','b'])
s2=Series([2,3,4], index=['c','d','e'])
s3=Series([5,6], index=['f','g'])

In [39]:
pd.concat([s1,s2,s3],axis=0)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [42]:
s4=pd.concat([s1*5, s3])
pd.concat([s1,s4], axis=0)

a    0
b    1
a    0
b    5
f    5
g    6
dtype: int64

In [40]:
pd.concat([s1,s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

In [41]:
s4

a    0
b    5
f    5
g    6
dtype: int64

In [44]:
pd.concat([s1,s4], axis=1, join_axes=[['a','c','b','f']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
f  NaN  5.0

In [45]:
result = pd.concat([s1,s1,s3],keys=['one','two','three'])

In [46]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [47]:
pd.concat([s1,s2,s3], axis=1, keys=['one','two','three'])

E:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [48]:
df1=DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])
df2=DataFrame(5+np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])
pd.concat([df1,df2], axis=1, keys=['level1','level2'])

E:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  This is separate from the ipykernel package so we can avoid doing imports until


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [49]:
df2

three  four
a      5     6
c      7     8

In [51]:
a=Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])
b=Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])
b[-1]=np.nan
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [52]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [53]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [54]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [55]:
df1=DataFrame({'a':[1.,np.nan,5,np.nan],'b':[np.nan,2.,np.nan,6.],'c':range(2,18,4)})
df2=DataFrame({'a':[5.,4.,np.nan,3,7],'b':[np.nan,3,4,6,8]})
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [57]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [58]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [59]:
data=DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['Ohio','Colorado'],name='state'),
    columns=pd.Index(['one','two','three'], name='number'))

In [62]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [60]:
result=data.stack()

In [61]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [63]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [66]:
data=DataFrame({'k1':['one']*3+['two']*4,'k2':[1,1,2,3,3,4,4]})

In [67]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [68]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [69]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [71]:
data['v11']=range(7)

In [72]:
data

k1  k2  v11
0  one   1    0
1  one   1    1
2  one   2    2
3  two   3    3
4  two   3    4
5  two   4    5
6  two   4    6

In [73]:
data.drop_duplicates(['k1'])

k1  k2  v11
0  one   1    0
3  two   3    3

In [76]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v11
1  one   1    1
2  one   2    2
4  two   3    4
6  two   4    6

In [88]:
data=DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [78]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Postrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [79]:
meat_to_animal={'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}

In [80]:
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [91]:
data['animal']=data['food'].map(str.lower).map(meat_to_animal)

In [92]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [89]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [94]:
data=Series([1.,-999,2.,-999,-1000,3])

In [95]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [96]:
data.replace([-999,-1000], np.nan)


0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [97]:
data.replace([-999,-1000],[np.nan,0])


0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [98]:
data.replace({-999:np.nan,-1000:0})


0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [99]:
data=DataFrame(np.arange(12).reshape((3,4)),
    index=['Ohio','Colorado','New York'],
    columns=['one','two','three','four'])
data.index.map(str.upper)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [100]:
data.index=data.index.map(str.upper)


In [101]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [102]:
data.rename(index=str.title, columns=str.upper)


ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [103]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [104]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]


In [105]:
bins=[18,25,35,60,100]
cats=pd.cut(ages, bins)

In [106]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [109]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [110]:
group_names=['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [113]:
data=np.random.rand(20)
pd.cut(data, 4, precision=3)

[(0.497, 0.745], (0.497, 0.745], (0.497, 0.745], (0.249, 0.497], (0.497, 0.745], ..., (0.497, 0.745], (0.745, 0.992], (0.745, 0.992], (0.497, 0.745], (0.745, 0.992]]
Length: 20
Categories (4, interval[float64]): [(0.000812, 0.249] < (0.249, 0.497] < (0.497, 0.745] < (0.745, 0.992]]

In [112]:
data

array([0.84845216, 0.41795836, 0.08801949, 0.80477997, 0.06691531,
       0.08224706, 0.97775143, 0.51917026, 0.27296637, 0.68791694,
       0.52865007, 0.51699842, 0.14026352, 0.4417365 , 0.9336158 ,
       0.53633533, 0.37932759, 0.56199075, 0.79181628, 0.92016273])

In [120]:
data=np.random.randn(10)
cats=pd.qcut(data,4)  #按四分位数进行切割
pd.value_counts(cats)

(0.0581, 0.326]     3
(-1.636, -0.832]    3
(-0.101, 0.0581]    2
(-0.832, -0.101]    2
dtype: int64

In [122]:
pd.cut(data,[0,0.1,0.5,0.9,1.])


[NaN, NaN, NaN, (0.1, 0.5], (0.0, 0.1], NaN, NaN, (0.0, 0.1], NaN, (0.1, 0.5]]
Categories (4, interval[float64]): [(0.0, 0.1] < (0.1, 0.5] < (0.5, 0.9] < (0.9, 1.0]]

In [121]:
data

array([-0.47390939, -0.02655757, -0.95129813,  0.18443406,  0.02448783,
       -0.17591112, -1.41776195,  0.06933073, -1.63475776,  0.32589546])

In [126]:

data=DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.020010    -0.017475     0.019226     0.007853
std       0.972193     0.959177     1.029013     1.015171
min      -3.393109    -3.621639    -3.303552    -2.750366
25%      -0.650279    -0.622368    -0.636212    -0.682188
50%       0.001894    -0.012083     0.011980    -0.012399
75%       0.678134     0.663745     0.691170     0.685328
max       3.561219     2.999190     3.193371     3.142285

In [128]:
col=data[3]

In [129]:
col[np.abs(col)>3]

533    3.077068
575    3.142285
Name: 3, dtype: float64

In [133]:
data[(np.abs(data)>3).any(1)]


0         1         2         3
228 -3.372347  0.420341  1.010951  0.459729
254 -3.393109 -0.098218 -0.451761 -0.385110
289  1.107966 -0.375666  3.193371  2.006304
404  2.214589 -0.279655  3.177053 -0.102075
437 -1.168550  0.522978  3.158873  0.051351
533 -0.104497  0.058140  1.153220  3.077068
575  0.345315  0.688694  2.158329  3.142285
672 -0.299503 -3.621639  0.375278 -0.813703
690  3.027240 -0.216031 -0.540040 -0.424454
746 -1.243493 -0.621747 -3.303552 -0.544853
838  0.058255 -3.214030  1.013550  0.056364
973  3.561219 -0.810016 -0.088040 -1.546873

In [134]:
data[np.abs(data)>3]=np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.020187    -0.016639     0.019001     0.007634
std       0.967683     0.956346     1.026493     1.014510
min      -3.000000    -3.000000    -3.000000    -2.750366
25%      -0.650279    -0.622368    -0.636212    -0.682188
50%       0.001894    -0.012083     0.011980    -0.012399
75%       0.678134     0.663745     0.691170     0.685328
max       3.000000     2.999190     3.000000     3.000000

In [143]:
df=DataFrame(np.arange(5*4).reshape(5,4))
sampler=np.random.permutation(5)

In [136]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [144]:
sampler

array([3, 1, 0, 4, 2])

In [145]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11

In [153]:
df.take(np.random.permutation(len(df)))[:3]


0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3

In [154]:
bag=np.array([5,7,-1,6,4])


In [155]:
bag

array([ 5,  7, -1,  6,  4])

In [156]:
sampler=np.random.randint(0,len(bag),size=10)


In [157]:
sampler

array([0, 2, 4, 4, 0, 1, 2, 1, 2, 2])