In [1]:
from pandas import Series,DataFrame
import pandas as pd

In [19]:
obj2=Series([4,7,-5,3],index=['d','b','a','c'])


In [20]:
obj2['a']

-5

In [21]:
obj2['d']=6

In [22]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [24]:
pop={'Nevada':{2001:2.4, 2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}


In [25]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [26]:
frame3=DataFrame(pop)

In [27]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [28]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [29]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [50]:
pd.DataFrame(pop,index=[2000,2001,2002,2003])

AttributeError: 'list' object has no attribute 'astype'

In [66]:
d = {'one':{'a':1,'b':2,'c':3}, 'two':{'a':1,'b':2,'c':3,'d':4}}

In [68]:
DataFrame(d, index={'d':1, 'b':2, 'a':3})

AttributeError: 'dict' object has no attribute 'astype'

In [70]:
obj2=Series([4,7,-5,3],index=['d','b','a','c'])


In [71]:
obj2[obj2>0]


d    4
b    7
c    3
dtype: int64

In [72]:
obj2*2


d     8
b    14
a   -10
c     6
dtype: int64

In [73]:
'b' in obj2


True

In [75]:
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=Series(sdata)


In [77]:
states=['California','Ohio','Oregon','Texas']


In [78]:
obj4=Series(sdata,index=states)


In [79]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [80]:
pd.isnull(obj4)


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [81]:
obj3+obj4


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [83]:
obj4.name='人口'


In [85]:
obj4.index.name='州'


In [86]:
obj4

州
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: 人口, dtype: float64

In [89]:
obj4.values.name='renshu'

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [90]:
obj4.index=['Bob','Steve','Jeff','Ryan']


In [91]:
obj4

Bob          NaN
Steve    35000.0
Jeff     16000.0
Ryan     71000.0
Name: 人口, dtype: float64

In [93]:
print(obj4.index.name)

None


In [94]:
obj4['Bob']=1

In [95]:
obj4

Bob          1.0
Steve    35000.0
Jeff     16000.0
Ryan     71000.0
Name: 人口, dtype: float64

In [99]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}
frame=DataFrame(data)


In [97]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [101]:
frame2=DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])


In [102]:
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN


In [105]:
frame2.year


one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [108]:
frame2.loc['three']


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [110]:
frame2['debt']=16.5


In [111]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [117]:
frame2['debt']=numpy.arange(5.)


In [114]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [119]:
val=Series([-1.2,-1.5,-1.7], index=['two','four','five'])


In [121]:
frame2['debt']=val


In [122]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [123]:
frame2['eastern']=frame2.state=='Ohio'


In [124]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [125]:
frame2.columns


Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [127]:
pdata={'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}


In [128]:
DataFrame(pdata)


Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [129]:
frame3.index.name='year'; frame3.columns.name='state'


In [130]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [131]:
frame3.values


array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [132]:
frame2.values


array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, -1.2, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -1.5, False],
       [2002, 'Nevada', 2.9, -1.7, False]], dtype=object)

In [134]:
obj=Series(range(3),index=['a','b','c'])


In [135]:
index=obj.index


In [137]:
print(index)

Index(['a', 'b', 'c'], dtype='object')


In [138]:
print(index[1:])


Index(['b', 'c'], dtype='object')


In [139]:
index[1]='d'


TypeError: Index does not support mutable operations

In [140]:
a = numpy.arange(16).reshape((4,4))

In [168]:
r = [(-2 if a>5 else 2)]

TypeError: '>' not supported between instances of 'zip' and 'int'

In [162]:
zip(a)

In [164]:
c = numpy.random.randn(2,2)

In [165]:
c

array([[ 0.63130805, -1.26205599],
       [-0.89117298,  0.77194231]])

In [186]:
r = [(-2 if c>0 else 2)for c in c]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [174]:
r = numpy.where(c>0,2,-2)

In [175]:
c

array([[ 0.63130805, -1.26205599],
       [-0.89117298,  0.77194231]])

In [176]:
r

array([[ 2, -2],
       [-2,  2]])

In [157]:
x=numpy.array([1.1,2.2,3.3])

In [158]:
x

array([1.1, 2.2, 3.3])

In [159]:
zip(x)

In [152]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [151]:
r

[2]

In [183]:
index=pd.Index(numpy.arange(3))


In [184]:
obj2=Series([1.5,-2.5,0], index=index)


In [191]:
frame=DataFrame(numpy.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])


In [199]:
frame.reindex(['a','b','c','d'])


Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [197]:
frame2

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [193]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [194]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [200]:
obj=Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj2=obj.reindex(['a','b','c','d','e'])


In [201]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [202]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [203]:
obj.reindex(['a','b','c','d','e'], fill_value=0)


a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [204]:
obj3=Series(['blue','purple','yellow'], index=[0,2,4])


In [205]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [206]:
obj3.reindex(range(6),method='ffill')


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [208]:
frame=DataFrame(numpy.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame2=frame.reindex(['a','b','c','d'])


In [209]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [210]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [211]:
states=['Texas','Utah','California']
frame.reindex(columns=states)


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [218]:
frame.reindex(index=['a','b','c','d'],columns=states)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [216]:
frame.ix[['a','b','c','d'], states]


E:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
E:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [220]:
obj=Series(numpy.arange(5.),index=['a','b','c','d','e'])


In [221]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [222]:
new_obj=obj.drop('c')


In [223]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [224]:
obj.drop(['d','c'])


a    0.0
b    1.0
e    4.0
dtype: float64

In [226]:
data=DataFrame(numpy.arange(16).reshape((4,4)),
        index=['Ohio','Colorado','Utah','New York'],
        columns=['one','two','three','four'])


In [227]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [228]:
data.drop(['Colorado','Ohio'])


one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [4]:
from pandas import Series,DataFrame
import numpy
data=DataFrame(numpy.arange(16).reshape((4,4)),
        index=['Ohio','Colorado','Utah','New York'],
        columns=['one','two','three','four'])


In [6]:
data.drop('two',axis=0)


KeyError: "labels ['two'] not contained in axis"

In [8]:
data.drop(['two','four'],axis=1)


one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [9]:
obj=Series(numpy.arange(4.),index=['a','b','c','d'])


In [11]:
print (obj[2:4])


c    2.0
d    3.0
dtype: float64


In [12]:
print (obj[[1,3]])


b    1.0
d    3.0
dtype: float64
