In [1]:
import numpy as np
data1=[6,7.5,8,0,1]

In [2]:
arr1=np.array(data1)

In [3]:
data2=[[1,2,3,4],[5,6,7,8]]

In [4]:
arr2=np.array(data2)

In [6]:
arr1.ndim

1

In [8]:
arr1.shape

(5,)

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr=np.array([1,2,3,4,5])
arr.dtype
float_arr=arr.astype(np.float64)
float_arr.dtype


dtype('float64')

In [13]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [14]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [15]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [18]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([1,1,1,1])
arr3=np.array([1,2])


In [22]:
arr1*arr3


ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [20]:
arr1-arr2


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
arr1-arr3


ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [23]:
arr=np.arange(10)
arr[5:8]=12
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [25]:
arr_slice=arr[5:8]
arr_slice[1]=12345
print(arr)


[    0     1     2     3     4    12 12345    12     8     9]


In [26]:
arr_slice[:]=64


In [27]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [37]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(data[names=='Bob'])


[[ 1.2118265   0.01764252  0.11500053  0.51325634]
 [ 0.45214074 -0.92227264 -0.15802719  0.80092425]]


In [41]:
from numpy import random 


SyntaxError: invalid syntax (<ipython-input-41-b2c240e6a889>, line 1)

In [42]:
from random import randn

ImportError: cannot import name 'randn'

In [43]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(data[names=='Bob'])

[[ 0.66239889 -0.34765636 -1.69153988  1.68305903]
 [-0.00553828  0.93495258  0.28503271  0.98539088]]


In [46]:
data[names=='Bob', 2:]


array([[-1.69153988,  1.68305903],
       [ 0.28503271,  0.98539088]])

In [49]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr[[4,3,0,6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [51]:
arr=np.arange(32).reshape((8,4))
arr[[1,5,7,2]][:,[0,3,1,2]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [52]:
arr=np.arange(15).reshape((3,5))
arr.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [53]:
arr=np.random.randn(6,3)
np.dot(arr.T, arr)


array([[ 2.14629543,  0.61126672,  0.85407905],
       [ 0.61126672,  4.65234398, -3.13319106],
       [ 0.85407905, -3.13319106,  8.21363522]])

In [58]:
arr=np.arange(16).reshape((2,2,4))

In [59]:
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [77]:
arr.transpose((1,2,0))


array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])